print("Введите первую переменную")
a = int(input())
print("Введите вторую переменную")
b = int(input())
print("Сумма равна ", a+b)
print("Разность равна ", a-b)
print("Произведение ", a*b)
print("Частое ", a/b)